name: jiji
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  hexcolor: ^1.0.4
  intro_slider: ^2.3.3
  otp_text_field:
  

  share: ^0.6.5+2

  image_picker: ^0.6.7+11



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

